sudo: required
services:
  - docker

before_install:
  - docker build -t ranuon98/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ranuon98/complex-test npm test

after_success:
  - docker build -t ranuon98/multi-client ./client
  - docker build -t ranuon98/multi-server ./server
  - docker build -t ranuon98/multi-nginx ./nginx
  - docker build -t ranuon98/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ranuon98/multi-client
  - docker push ranuon98/multi-server
  - docker push ranuon98/multi-nginx
  - docker push ranuon98/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-565884025670'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY